### ISSUE TITLE
cmake_path is new in cmake 3.20 and not available in Ubuntu 20.04

### ISSUE THREAD

**Issue by Dyymon** [qcr/armer_msgs#1]
Hi,

building failed in cmakelists.txt on line 12. The reason was that `cmake_path` is new in cmake 3.20 and not available in Ubuntu 20.04. The build succeeded when I updated cmake using the ppa repo of cmake.

Best,
Jan

**Comment by suddrey-qut** [comment]
Fixed in commit 8f7508
